# Site settings
title: "脱线道士维克多"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wjp2013.github.io" # the base hostname & protocol for your site
github_username: wjp2013

timezone: Beijing
gems: ['jekyll-paginate', 'pygments.rb']

# Build settings
highlighter: pygments
permalink: /:categories/:title/

# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables

paginate: 20

