# Site settings
title: "脱线道士维克多"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wjp2013.github.io" # the base hostname & protocol for your site
github_username: wjp2013

# Build settings
highlighter: pygments
permalink: /:title/

markdown: kramdown
redcarpet:
  extensions:
    - fenced_code_blocks
